// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from "dedot/contracts";
import type { InkPrimitivesLangError } from "./types.js";

export interface ConstructorQuery<
  Type extends MetadataType,
> extends GenericConstructorQuery<Type> {
  /**
   *
   * @param {H160} configAddress
   * @param {H160} reputationAddress
   * @param {H160} lendingPoolAddress
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      configAddress: H160,
      reputationAddress: H160,
      lendingPoolAddress: H160,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
