// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { VouchError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Vouch for a borrower by staking stars and capital
   *
   * @param {AccountId32Like} borrower
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {ContractCallOptions} options
   *
   * @selector 0x42299f24
   **/
  vouchFor: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      stars: number,
      capitalPercent: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get count of active vouches for a borrower
   *
   * @param {AccountId32Like} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x479d9ad6
   **/
  getVouchesFor: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Get all voucher addresses for a borrower
   *
   * @param {AccountId32Like} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x964f1124
   **/
  getAllVouchers: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<AccountId32>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Resolve all vouch relationships for a borrower upon loan completion
   *
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {ContractCallOptions} options
   *
   * @selector 0x11b5e79c
   **/
  resolveAll: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      success: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;
}
