// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result, AccountId32Like, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { VouchError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Set the loan manager address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManager
   * @param {ContractCallOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractQueryCall<
    (
      loanManager: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Vouch for a specific loan (called by loan_manager after validation)
   * Only callable by loan_manager
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrower
   * @param {AccountId32Like} voucher
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0xdeb14168
   **/
  vouchForLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      borrower: AccountId32Like,
      voucher: AccountId32Like,
      stars: number,
      capitalPercent: number,
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get count of active vouches for a specific loan
   *
   * @param {bigint} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0x0d6fc8ed
   **/
  getVouchesForLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Get all voucher addresses for a specific loan
   *
   * @param {bigint} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0x52e5c4de
   **/
  getVouchersForLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<AccountId32>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get total staked capital for a specific loan
   * Returns the sum of all staked capital from active vouches for this loan
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0xd3d77eab
   **/
  getTotalStakedCapitalForLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      borrower: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get count of active vouches for a borrower (backward compatibility)
   *
   * @param {AccountId32Like} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x479d9ad6
   **/
  getVouchesFor: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Get all voucher addresses for a borrower (backward compatibility)
   *
   * @param {AccountId32Like} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x964f1124
   **/
  getAllVouchers: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<AccountId32>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Resolve all vouch relationships for a loan upon loan completion
   * Only callable by the authorized loan manager contract
   * loan_amount: The loan amount (in 10 decimals). Only used when success=false to calculate recovery.
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {bigint} loanAmount
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0xac28779b
   **/
  resolveLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      borrower: AccountId32Like,
      success: boolean,
      loanAmount: bigint,
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Resolve all vouch relationships for a borrower (backward compatibility)
   * Only callable by the authorized loan manager contract
   *
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x11b5e79c
   **/
  resolveAll: GenericContractQueryCall<
    (
      borrower: AccountId32Like,
      success: boolean,
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], VouchError>, ContractCallResult>
    >,
    Type
  >;
}
