// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Vouch for a borrower by staking stars and capital
   *
   * @param {AccountId32Like} borrower
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {ContractTxOptions} options
   *
   * @selector 0x42299f24
   **/
  vouchFor: GenericContractTxCall<
    (
      borrower: AccountId32Like,
      stars: number,
      capitalPercent: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Resolve all vouch relationships for a borrower upon loan completion
   *
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {ContractTxOptions} options
   *
   * @selector 0x11b5e79c
   **/
  resolveAll: GenericContractTxCall<
    (
      borrower: AccountId32Like,
      success: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
