// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Set the loan manager address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManager
   * @param {ContractTxOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractTxCall<
    (
      loanManager: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Vouch for a specific loan (called by loan_manager after validation)
   * Only callable by loan_manager
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrower
   * @param {AccountId32Like} voucher
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0xdeb14168
   **/
  vouchForLoan: GenericContractTxCall<
    (
      loanId: bigint,
      borrower: AccountId32Like,
      voucher: AccountId32Like,
      stars: number,
      capitalPercent: number,
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Resolve all vouch relationships for a loan upon loan completion
   * Only callable by the authorized loan manager contract
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0xac28779b
   **/
  resolveLoan: GenericContractTxCall<
    (
      loanId: bigint,
      borrower: AccountId32Like,
      success: boolean,
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Resolve all vouch relationships for a borrower (backward compatibility)
   * Only callable by the authorized loan manager contract
   *
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x11b5e79c
   **/
  resolveAll: GenericContractTxCall<
    (
      borrower: AccountId32Like,
      success: boolean,
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
