// Generated by dedot cli

import type { H160, AccountId32Like, AccountId32 } from "dedot/codecs";

export type InkStorageLazy = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type InkStorageLazyMapping = {};

export type VouchVouchRelationship = {
  loanId: bigint;
  stakedStars: number;
  stakedCapital: bigint;
  createdAt: bigint;
  status: VouchStatus;
};

export type VouchStatus = "Active" | "Fulfilled" | "Defaulted";

export type Vouch = {
  config: H160;
  reputation: H160;
  lendingPool: H160;
  loanManager: { get(): Promise<H160 | undefined | undefined> };
  relationships: {
    get(
      arg: [AccountId32Like, AccountId32Like],
    ): Promise<VouchVouchRelationship | undefined>;
  };
  loanVouchers: { get(arg: bigint): Promise<Array<AccountId32> | undefined> };
  borrowerExposure: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  borrowerVouchers: {
    get(arg: AccountId32Like): Promise<Array<AccountId32> | undefined>;
  };
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type VouchError =
  | "NotEnoughStars"
  | "NotEnoughCapital"
  | "UnableToVouch"
  | "ZeroAmount"
  | "ExposureCapExceeded"
  | "AlreadyResolved"
  | "RelationshipNotFound"
  | "Unauthorized";
