/**
 * Contract metadata exports
 * 
 * These metadata files are required for interacting with ink! contracts.
 * They contain the ABI (Application Binary Interface) definitions.
 * 
 * To generate these metadata files, use the dedot CLI:
 * - dedot typink -m <path-to-contract.json>
 * 
 * Place the generated .json metadata files in this directory and import them here.
 */

// Import contract metadata JSON files
// These should be the .contract or .json files generated by cargo-contract
import configMetadata from './config.json';
import lendingPoolMetadata from './lending_pool.json';
import reputationMetadata from './reputation.json';
import vouchMetadata from './vouch.json';

export const metadata = {
  config: configMetadata,
  lendingPool: lendingPoolMetadata,
  reputation: reputationMetadata,
  vouch: vouchMetadata,
} as const;

export { configMetadata, lendingPoolMetadata, reputationMetadata, vouchMetadata };
