// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  Type extends MetadataType,
> extends GenericContractEvents<Type> {
  /**
   *
   *
   **/
  RepaymentReceived: GenericContractEvent<
    "RepaymentReceived",
    {
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Events for lending pool actions
   *
   *
   **/
  Deposit: GenericContractEvent<
    "Deposit",
    {
      /**
       *
       * @indexed: false
       **/
      depositor: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  Withdraw: GenericContractEvent<
    "Withdraw",
    {
      /**
       *
       * @indexed: false
       **/
      withdrawer: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;
}
