// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from "dedot/types";
import type { InkGenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, LendingPool } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: LendingPoolContractApi
 * @contractName: lending_pool
 * @contractVersion: 0.1.0
 * @authors: Fabian Sanchez <fabiansanchezd@outlook.com>
 * @language: ink! 6.0.0-beta.1
 **/
export interface LendingPoolContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: "ink";
  query: ContractQuery<"ink">;
  tx: ContractTx<"ink">;
  constructorQuery: ConstructorQuery<"ink">;
  constructorTx: ConstructorTx<LendingPoolContractApi, "ink">;
  events: ContractEvents<"ink">;
  storage: {
    root(): Promise<LendingPool>;
    lazy(): WithLazyStorage<LendingPool>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: LendingPool;
    LazyStorage: WithLazyStorage<LendingPool>;
    LangError: InkPrimitivesLangError;
  };
}
