// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  LendingPoolError,
  InkPrimitivesLangError,
  LendingPoolUserInfo,
} from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Set the vouch contract address (can only be set once)
   * This should be called after the Vouch contract is deployed
   *
   * @param {H160} vouchAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x3613a884
   **/
  setVouchContract: GenericContractQueryCall<
    (
      vouchAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Set the loan manager contract address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractQueryCall<
    (
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Deposits to the lending pool
   *
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x2d10c9bd
   **/
  deposit: GenericContractQueryCall<
    (
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Withdraw funds from the lending pool
   * amount: in 10 decimals (storage format)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x410fcc9d
   **/
  withdraw: GenericContractQueryCall<
    (
      amount: bigint,
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x133e6c7c
   **/
  getCurrentRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get user's accrued yield (read-only, doesn't accrue interest)
   * Returns yield in 18 decimals (chain format)
   * Note: This calculates yield based on current state without accruing interest.
   * For up-to-date yield, call accrue_interest_and_get_user_yield instead.
   *
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xdb8df080
   **/
  getUserYield: GenericContractQueryCall<
    (
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get user's accrued yield and ensure interest is up-to-date
   * Returns yield in 18 decimals (chain format)
   * This version accrues interest before calculating yield for accurate results
   *
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x8e1f3e45
   **/
  accrueInterestAndGetUserYield: GenericContractQueryCall<
    (
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get user's deposit balance
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x3ebb50fa
   **/
  getUserDeposit: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xddd7e6c3
   **/
  getTotalLiquidity: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Disburse part of liquidity (add a borrow basically)
   * Only callable by the authorized loan manager contract
   * amount: in 10 decimals (storage format)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} to
   * @param {ContractCallOptions} options
   *
   * @selector 0x28217c4a
   **/
  disburse: GenericContractQueryCall<
    (
      amount: bigint,
      to: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Repay a loan (reduce borrowed amount)
   * amount: in 18 decimals (chain format, matching transferred_value)
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x72874674
   **/
  receiveRepayment: GenericContractQueryCall<
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Slash part of the position of a voucher
   * Only callable by the authorized vouch contract
   * amount: in 10 decimals (storage format)
   * Note: This function also decreases staked capital tracking automatically
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xd6170b15
   **/
  slashStake: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Handle default recovery: compare total slashed capital to loan amount
   * Only callable by the authorized vouch contract
   * total_slashed_capital: Total capital slashed from all vouchers (in 10 decimals)
   * loan_amount: The loan amount that defaulted (in 10 decimals)
   *
   * Logic:
   * - If slashed capital >= loan amount: Add loan amount back to liquidity (covers the default)
   * - If slashed capital < loan amount: Add slashed amount back to liquidity, add deficit to reserved_funds
   *
   * @param {bigint} totalSlashedCapital
   * @param {bigint} loanAmount
   * @param {ContractCallOptions} options
   *
   * @selector 0x738e7f80
   **/
  handleDefaultRecovery: GenericContractQueryCall<
    (
      totalSlashedCapital: bigint,
      loanAmount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Increase staked capital for a user (only callable by vouch contract)
   * amount: in 10 decimals (storage format)
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xdde18f09
   **/
  increaseStakedCapital: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Decrease staked capital for a user (only callable by vouch contract)
   * amount: in 10 decimals (storage format)
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x96a5d2ba
   **/
  decreaseStakedCapital: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get user's staked capital
   * Returns amount in 10 decimals (storage format)
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0xf6dddcc5
   **/
  getUserStakedCapital: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get comprehensive user information
   * Returns all user data including deposit, staked capital, available balance, and yield
   *
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xf499d5d0
   **/
  getUserInfo: GenericContractQueryCall<
    (
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<LendingPoolUserInfo, ContractCallResult>
    >,
    Type
  >;
}
