// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Result, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { LendingPoolError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Deposits to the lending pool
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2d10c9bd
   **/
  deposit: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Withdraw funds from the lending pool
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x410fcc9d
   **/
  withdraw: GenericContractQueryCall<
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x133e6c7c
   **/
  getCurrentRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get user's accrued yield
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xdb8df080
   **/
  getUserYield: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get user's deposit balance
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x3ebb50fa
   **/
  getUserDeposit: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xddd7e6c3
   **/
  getTotalLiquidity: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Disburse part of liquidity (add a borrow basically)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} to
   * @param {ContractCallOptions} options
   *
   * @selector 0x28217c4a
   **/
  disburse: GenericContractQueryCall<
    (
      amount: bigint,
      to: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Repay a loan (reduce borrowed amount)
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x72874674
   **/
  receiveRepayment: GenericContractQueryCall<
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Slash part of the position of a voucher
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xd6170b15
   **/
  slashStake: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LendingPoolError>,
        ContractCallResult
      >
    >,
    Type
  >;
}
