// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Set the vouch contract address (can only be set once)
   * This should be called after the Vouch contract is deployed
   *
   * @param {H160} vouchAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x3613a884
   **/
  setVouchContract: GenericContractTxCall<
    (
      vouchAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set the loan manager contract address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractTxCall<
    (
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Deposits to the lending pool
   *
   * @param {AccountId32Like} accountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x2d10c9bd
   **/
  deposit: GenericContractTxCall<
    (
      accountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Withdraw funds from the lending pool
   * amount: in 10 decimals (storage format)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} accountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x410fcc9d
   **/
  withdraw: GenericContractTxCall<
    (
      amount: bigint,
      accountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Get user's accrued yield and ensure interest is up-to-date
   * Returns yield in 18 decimals (chain format)
   * This version accrues interest before calculating yield for accurate results
   *
   * @param {AccountId32Like} accountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x8e1f3e45
   **/
  accrueInterestAndGetUserYield: GenericContractTxCall<
    (
      accountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Disburse part of liquidity (add a borrow basically)
   * Only callable by the authorized loan manager contract
   * amount: in 10 decimals (storage format)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} to
   * @param {ContractTxOptions} options
   *
   * @selector 0x28217c4a
   **/
  disburse: GenericContractTxCall<
    (
      amount: bigint,
      to: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Repay a loan (reduce borrowed amount)
   * amount: in 18 decimals (chain format, matching transferred_value)
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x72874674
   **/
  receiveRepayment: GenericContractTxCall<
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Slash part of the position of a voucher
   * Only callable by the authorized vouch contract
   * amount: in 10 decimals (storage format)
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xd6170b15
   **/
  slashStake: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
