// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Deposits to the lending pool
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x2d10c9bd
   **/
  deposit: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Withdraw funds from the lending pool
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x410fcc9d
   **/
  withdraw: GenericContractTxCall<
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Get user's accrued yield
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xdb8df080
   **/
  getUserYield: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Disburse part of liquidity (add a borrow basically)
   *
   * @param {bigint} amount
   * @param {AccountId32Like} to
   * @param {ContractTxOptions} options
   *
   * @selector 0x28217c4a
   **/
  disburse: GenericContractTxCall<
    (
      amount: bigint,
      to: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Repay a loan (reduce borrowed amount)
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x72874674
   **/
  receiveRepayment: GenericContractTxCall<
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Slash part of the position of a voucher
   *
   * @param {AccountId32Like} user
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xd6170b15
   **/
  slashStake: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
