// Generated by dedot cli

import type { H160, AccountId32Like } from "dedot/codecs";

export type InkStorageLazy = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type InkStorageLazyMapping = {};

export type LendingPool = {
  config: H160;
  totalLiquidity: { get(): Promise<bigint | undefined> };
  totalBorrowed: { get(): Promise<bigint | undefined> };
  reservedFunds: { get(): Promise<bigint | undefined> };
  userDeposits: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  lastUpdate: { get(): Promise<bigint | undefined> };
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type LendingPoolError =
  | "ZeroAmount"
  | "NegativeAmount"
  | "Overflow"
  | "UnavailableFunds"
  | "TransactionFailed"
  | "AmountMismatch";
