// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ConstructorTx<
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<Type> {
  /**
   *
   * @param {H160} configAddress
   * @param {H160} reputationAddress
   * @param {H160} lendingPoolAddress
   * @param {H160} vouchAddress
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    (
      configAddress: H160,
      reputationAddress: H160,
      lendingPoolAddress: H160,
      vouchAddress: H160,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ContractApi>,
    Type
  >;
}
