// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { BytesLike, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { LoanManagerError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Request a loan from the lending pool
   *
   * @param {bigint} amount
   * @param {BytesLike} purpose
   * @param {ContractCallOptions} options
   *
   * @selector 0x3177501d
   **/
  requestLoan: GenericContractQueryCall<
    (
      amount: bigint,
      purpose: BytesLike,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Check if a loan is overdue and handle defaulting
   * Slashes borrower's stars and resolves vouches as failed
   *
   * @param {bigint} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractQueryCall<
    (
      loanId: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;
}
