// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { BytesLike } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Request a loan from the lending pool
   *
   * @param {bigint} amount
   * @param {BytesLike} purpose
   * @param {ContractTxOptions} options
   *
   * @selector 0x3177501d
   **/
  requestLoan: GenericContractTxCall<
    (
      amount: bigint,
      purpose: BytesLike,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Check if a loan is overdue and handle defaulting
   * Slashes borrower's stars and resolves vouches as failed
   *
   * @param {bigint} loanId
   * @param {ContractTxOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractTxCall<
    (
      loanId: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
