// Generated by dedot cli

import type { AccountId32, Bytes, H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type LoanManagerLoan = {
  loanId: bigint;
  borrower: AccountId32;
  amount: bigint;
  interestRate: bigint;
  term: bigint;
  purpose: Bytes;
  startTime: bigint;
  status: LoanManagerLoanStatus;
  vouchers: Array<AccountId32>;
};

export type LoanManagerLoanStatus = "Active" | "Repaid" | "Defaulted";

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type InkStorageLazy = {};

export type LoanManager = {
  config: H160;
  reputation: H160;
  lendingPool: H160;
  vouch: H160;
  loans: { get(arg: bigint): Promise<LoanManagerLoan | undefined> };
  nextLoanId: { get(): Promise<bigint | undefined> };
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type LoanManagerError =
  | "InsufficientReputation"
  | "InsufficientVouches"
  | "ZeroAmount"
  | "DisbursementFailed"
  | "LoanNotFound"
  | "LoanNotActive"
  | "LoanNotOverdue"
  | "SlashFailed"
  | "ResolveFailed";
