// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, AccountId32Like } from "dedot/codecs";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ConstructorTx<
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<Type> {
  /**
   *
   * @param {H160} configAddress
   * @param {AccountId32Like} adminAccountId
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    (
      configAddress: H160,
      adminAccountId: AccountId32Like,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ContractApi>,
    Type
  >;
}
