// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { InkPrimitivesLangError, ReputationError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Function to get stars of a user
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x44bf36de
   **/
  getStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Function to add stars to a user
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x6e66303d
   **/
  addStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to check if a user can vouch based on their stars
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x0ad5e3fa
   **/
  canVouch: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xf7ed7340
   **/
  slashStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to stake stars for a user
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe3be7b0
   **/
  stakeStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to unstake stars for a user after vouching and loan is repaid successfully
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {boolean} success
   * @param {ContractCallOptions} options
   *
   * @selector 0xd2519ab6
   **/
  unstakeStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      success: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;
}
