// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result, AccountId32Like, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { ReputationError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Set the vouch contract address (can only be set once)
   * This should be called after the Vouch contract is deployed
   *
   * @param {H160} vouchAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x3613a884
   **/
  setVouchContract: GenericContractQueryCall<
    (
      vouchAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set the loan manager contract address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractQueryCall<
    (
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to get stars of a user
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x44bf36de
   **/
  getStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Function to add stars to a user
   * Only callable by authorized contracts (loan manager or vouch contract)
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x6e66303d
   **/
  addStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to check if a user can vouch based on their stars
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x0ad5e3fa
   **/
  canVouch: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Slash stars from a user (penalty for defaults)
   * Only callable by the authorized loan manager contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xf7ed7340
   **/
  slashStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to stake stars for a user
   * Only callable by the authorized vouch contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe3be7b0
   **/
  stakeStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Function to unstake stars for a user after vouching and loan is repaid successfully
   * Only callable by the authorized vouch contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {ContractCallOptions} options
   *
   * @selector 0xd2519ab6
   **/
  unstakeStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      borrower: AccountId32Like,
      success: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Admin function: Set stars for a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {number} stars
   * @param {ContractCallOptions} options
   *
   * @selector 0x1010203b
   **/
  adminSetStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      stars: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Admin function: Add stars to a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xbdb6df2c
   **/
  adminAddStars: GenericContractQueryCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Admin function: Unban a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x35b40fc4
   **/
  adminUnbanUser: GenericContractQueryCall<
    (
      user: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ReputationError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Admin function: Get admin address (for verification)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x57b8a8a7
   **/
  getAdmin: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<AccountId32, ContractCallResult>>,
    Type
  >;
}
