// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Function to add stars to a user
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x6e66303d
   **/
  addStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xf7ed7340
   **/
  slashStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Function to stake stars for a user
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xbe3be7b0
   **/
  stakeStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Function to unstake stars for a user after vouching and loan is repaid successfully
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {boolean} success
   * @param {ContractTxOptions} options
   *
   * @selector 0xd2519ab6
   **/
  unstakeStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      success: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
