// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Set the vouch contract address (can only be set once)
   * This should be called after the Vouch contract is deployed
   *
   * @param {H160} vouchAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x3613a884
   **/
  setVouchContract: GenericContractTxCall<
    (
      vouchAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set the loan manager contract address (can only be set once)
   * This should be called after the LoanManager contract is deployed
   *
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x87f1f66d
   **/
  setLoanManager: GenericContractTxCall<
    (
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Function to add stars to a user
   * Only callable by authorized contracts (loan manager or vouch contract)
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x6e66303d
   **/
  addStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Slash stars from a user (penalty for defaults)
   * Only callable by the authorized loan manager contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xf7ed7340
   **/
  slashStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Function to stake stars for a user
   * Only callable by the authorized vouch contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xbe3be7b0
   **/
  stakeStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Function to unstake stars for a user after vouching and loan is repaid successfully
   * Only callable by the authorized vouch contract
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {AccountId32Like} borrower
   * @param {boolean} success
   * @param {ContractTxOptions} options
   *
   * @selector 0xd2519ab6
   **/
  unstakeStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      borrower: AccountId32Like,
      success: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Admin function: Set stars for a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {number} stars
   * @param {ContractTxOptions} options
   *
   * @selector 0x1010203b
   **/
  adminSetStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      stars: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Admin function: Add stars to a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {number} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xbdb6df2c
   **/
  adminAddStars: GenericContractTxCall<
    (
      user: AccountId32Like,
      amount: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Admin function: Unban a user (for testing)
   * Only callable by admin
   *
   * @param {AccountId32Like} user
   * @param {ContractTxOptions} options
   *
   * @selector 0x35b40fc4
   **/
  adminUnbanUser: GenericContractTxCall<
    (
      user: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
