// Generated by dedot cli

import type { AccountId32, H160, AccountId32Like } from "dedot/codecs";

export type ReputationLoanStat = { amount: bigint; repaid: boolean };

export type ReputationVouchStat = {
  borrower: AccountId32;
  successful: boolean;
};

export type InkStorageLazyMapping = {};

export type ReputationUserReputation = {
  stars: number;
  starsAtStake: number;
  loanHistory: Array<ReputationLoanStat>;
  vouchHistory: Array<ReputationVouchStat>;
  creationTime: bigint;
  banned: boolean;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Reputation = {
  config: H160;
  userReps: {
    get(arg: AccountId32Like): Promise<ReputationUserReputation | undefined>;
  };
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type ReputationError =
  | "UserNotFound"
  | "InsufficientStars"
  | "InsufficientStakedStars"
  | "UserBanned";
