// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result } from "dedot/codecs";
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from "dedot/contracts";
import type { InkPrimitivesLangError } from "./types.js";

export interface ConstructorQuery<
  Type extends MetadataType,
> extends GenericConstructorQuery<Type> {
  /**
   * Constructor that initializes configuration with defaults and admin
   *
   * @param {AccountId32Like} adminAccountId
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      adminAccountId: AccountId32Like,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
