// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from "dedot/types";
import type { InkGenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, Config } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: ConfigContractApi
 * @contractName: config
 * @contractVersion: 0.1.0
 * @authors: Fabian Sanchez <fabiansanchezd@outlook.com>
 * @language: ink! 6.0.0-beta.1
 **/
export interface ConfigContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: "ink";
  query: ContractQuery<"ink">;
  tx: ContractTx<"ink">;
  constructorQuery: ConstructorQuery<"ink">;
  constructorTx: ConstructorTx<ConfigContractApi, "ink">;
  events: ContractEvents<"ink">;
  storage: {
    root(): Promise<Config>;
    lazy(): WithLazyStorage<Config>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Config;
    LazyStorage: WithLazyStorage<Config>;
    LangError: InkPrimitivesLangError;
  };
}
