// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32, Result, AccountId32Like } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { InkPrimitivesLangError, ConfigError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x57b8a8a7
   **/
  getAdmin: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<AccountId32, ContractCallResult>>,
    Type
  >;

  /**
   * Setter functions for configuration parameters
   *
   * @param {bigint} newRate
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x0a857f2e
   **/
  updateBaseInterestRate: GenericContractQueryCall<
    (
      newRate: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4ddf68a4
   **/
  getOptimalUtilization: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9505b812
   **/
  getSlope1: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xcf931887
   **/
  getSlope2: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x0eea1ead
   **/
  getExposureCap: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7dbf85cf
   **/
  getReserveFactor: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xfd33a0f6
   **/
  getMaxRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {bigint} newBoost
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x5e603b52
   **/
  updateBoost: GenericContractQueryCall<
    (
      newBoost: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} newMin
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x5bfb3671
   **/
  updateMinStarsToVouch: GenericContractQueryCall<
    (
      newMin: number,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x1967d257
   **/
  updateCooldownPeriod: GenericContractQueryCall<
    (
      newPeriod: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newTerm
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xc12b7115
   **/
  updateLoanTerm: GenericContractQueryCall<
    (
      newTerm: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newFactor
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x11315a5b
   **/
  updateLoanTierScalingFactor: GenericContractQueryCall<
    (
      newFactor: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xa8f93839
   **/
  updateLoanTier1MaxScaledAmount: GenericContractQueryCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xbc7cbd3c
   **/
  updateLoanTier2MaxScaledAmount: GenericContractQueryCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x3859f193
   **/
  updateLoanTier1Requirements: GenericContractQueryCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xa8d4f015
   **/
  updateLoanTier2Requirements: GenericContractQueryCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x68783f07
   **/
  updateLoanTier3Requirements: GenericContractQueryCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0xe10f7e85
   **/
  updateDefaultGracePeriod: GenericContractQueryCall<
    (
      newPeriod: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newDiscount
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x2548031c
   **/
  updateStarDiscountPercentPerStar: GenericContractQueryCall<
    (
      newDiscount: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x26756fd0
   **/
  updateMaxStarDiscountPercent: GenericContractQueryCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Getter functions for configuration parameters
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xef7a1277
   **/
  getBaseInterestRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf5aa3bfa
   **/
  getBoost: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2cc76f21
   **/
  getMinStarsToVouch: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7dd6b7d6
   **/
  getCooldownPeriod: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4ff736c1
   **/
  getLoanTerm: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for loan tier scaling factor
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x56cce0eb
   **/
  loanTierScalingFactor: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for tier 1 maximum scaled amount
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x187c9fc8
   **/
  loanTier1MaxScaledAmount: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for tier 2 maximum scaled amount
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x326d3a7c
   **/
  loanTier2MaxScaledAmount: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for tier 1 requirements (min_stars, min_vouches)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8a9ccfe7
   **/
  loanTier1Requirements: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[number, number], ContractCallResult>
    >,
    Type
  >;

  /**
   * Getter for tier 2 requirements (min_stars, min_vouches)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbbe0d06c
   **/
  loanTier2Requirements: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[number, number], ContractCallResult>
    >,
    Type
  >;

  /**
   * Getter for tier 3 requirements (min_stars, min_vouches)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xcc6a01fe
   **/
  loanTier3Requirements: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[number, number], ContractCallResult>
    >,
    Type
  >;

  /**
   * Getter for default grace period
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x99e99562
   **/
  getDefaultGracePeriod: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for star discount percent per star
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe1afb55
   **/
  getStarDiscountPercentPerStar: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Getter for maximum star discount percent
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x56c30805
   **/
  getMaxStarDiscountPercent: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;
}
