// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { ConfigError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Setter functions for configuration parameters
   *
   * @param {bigint} newRate
   * @param {ContractCallOptions} options
   *
   * @selector 0x0a857f2e
   **/
  updateBaseInterestRate: GenericContractQueryCall<
    (
      newRate: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newOptimal
   * @param {ContractCallOptions} options
   *
   * @selector 0x32e80b05
   **/
  updateOptimalUtilization: GenericContractQueryCall<
    (
      newOptimal: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newSlope
   * @param {ContractCallOptions} options
   *
   * @selector 0x18e98214
   **/
  updateSlope1: GenericContractQueryCall<
    (
      newSlope: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newSlope
   * @param {ContractCallOptions} options
   *
   * @selector 0x98841c75
   **/
  updateSlope2: GenericContractQueryCall<
    (
      newSlope: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newBoost
   * @param {ContractCallOptions} options
   *
   * @selector 0x5e603b52
   **/
  updateBoost: GenericContractQueryCall<
    (
      newBoost: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} newMin
   * @param {ContractCallOptions} options
   *
   * @selector 0x5bfb3671
   **/
  updateMinStarsToVouch: GenericContractQueryCall<
    (
      newMin: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {ContractCallOptions} options
   *
   * @selector 0x1967d257
   **/
  updateCooldownPeriod: GenericContractQueryCall<
    (
      newPeriod: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newCap
   * @param {ContractCallOptions} options
   *
   * @selector 0xef1525c5
   **/
  updateExposureCap: GenericContractQueryCall<
    (
      newCap: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} newFactor
   * @param {ContractCallOptions} options
   *
   * @selector 0x325a10c6
   **/
  updateReserveFactor: GenericContractQueryCall<
    (
      newFactor: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {ContractCallOptions} options
   *
   * @selector 0x79262ca5
   **/
  updateMaxRate: GenericContractQueryCall<
    (
      newMax: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], ConfigError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Getter functions for configuration parameters
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xef7a1277
   **/
  getBaseInterestRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4ddf68a4
   **/
  getOptimalUtilization: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9505b812
   **/
  getSlope1: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xcf931887
   **/
  getSlope2: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf5aa3bfa
   **/
  getBoost: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2cc76f21
   **/
  getMinStarsToVouch: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7dd6b7d6
   **/
  getCooldownPeriod: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x0eea1ead
   **/
  getExposureCap: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7dbf85cf
   **/
  getReserveFactor: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xfd33a0f6
   **/
  getMaxRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;
}
