// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Setter functions for configuration parameters
   *
   * @param {bigint} newRate
   * @param {ContractTxOptions} options
   *
   * @selector 0x0a857f2e
   **/
  updateBaseInterestRate: GenericContractTxCall<
    (
      newRate: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newOptimal
   * @param {ContractTxOptions} options
   *
   * @selector 0x32e80b05
   **/
  updateOptimalUtilization: GenericContractTxCall<
    (
      newOptimal: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newSlope
   * @param {ContractTxOptions} options
   *
   * @selector 0x18e98214
   **/
  updateSlope1: GenericContractTxCall<
    (
      newSlope: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newSlope
   * @param {ContractTxOptions} options
   *
   * @selector 0x98841c75
   **/
  updateSlope2: GenericContractTxCall<
    (
      newSlope: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newBoost
   * @param {ContractTxOptions} options
   *
   * @selector 0x5e603b52
   **/
  updateBoost: GenericContractTxCall<
    (
      newBoost: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newMin
   * @param {ContractTxOptions} options
   *
   * @selector 0x5bfb3671
   **/
  updateMinStarsToVouch: GenericContractTxCall<
    (
      newMin: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {ContractTxOptions} options
   *
   * @selector 0x1967d257
   **/
  updateCooldownPeriod: GenericContractTxCall<
    (
      newPeriod: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newCap
   * @param {ContractTxOptions} options
   *
   * @selector 0xef1525c5
   **/
  updateExposureCap: GenericContractTxCall<
    (
      newCap: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newFactor
   * @param {ContractTxOptions} options
   *
   * @selector 0x325a10c6
   **/
  updateReserveFactor: GenericContractTxCall<
    (
      newFactor: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {ContractTxOptions} options
   *
   * @selector 0x79262ca5
   **/
  updateMaxRate: GenericContractTxCall<
    (
      newMax: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
