// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Setter functions for configuration parameters
   *
   * @param {bigint} newRate
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x0a857f2e
   **/
  updateBaseInterestRate: GenericContractTxCall<
    (
      newRate: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newBoost
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x5e603b52
   **/
  updateBoost: GenericContractTxCall<
    (
      newBoost: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newMin
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x5bfb3671
   **/
  updateMinStarsToVouch: GenericContractTxCall<
    (
      newMin: number,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x1967d257
   **/
  updateCooldownPeriod: GenericContractTxCall<
    (
      newPeriod: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newTerm
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0xc12b7115
   **/
  updateLoanTerm: GenericContractTxCall<
    (
      newTerm: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newFactor
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x11315a5b
   **/
  updateLoanTierScalingFactor: GenericContractTxCall<
    (
      newFactor: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0xa8f93839
   **/
  updateLoanTier1MaxScaledAmount: GenericContractTxCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0xbc7cbd3c
   **/
  updateLoanTier2MaxScaledAmount: GenericContractTxCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x3859f193
   **/
  updateLoanTier1Requirements: GenericContractTxCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0xa8d4f015
   **/
  updateLoanTier2Requirements: GenericContractTxCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} minStars
   * @param {number} minVouches
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x68783f07
   **/
  updateLoanTier3Requirements: GenericContractTxCall<
    (
      minStars: number,
      minVouches: number,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newPeriod
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0xe10f7e85
   **/
  updateDefaultGracePeriod: GenericContractTxCall<
    (
      newPeriod: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newDiscount
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x2548031c
   **/
  updateStarDiscountPercentPerStar: GenericContractTxCall<
    (
      newDiscount: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newMax
   * @param {AccountId32Like} callerAccountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x26756fd0
   **/
  updateMaxStarDiscountPercent: GenericContractTxCall<
    (
      newMax: bigint,
      callerAccountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
