// Generated by dedot cli

import type { AccountId32 } from "dedot/codecs";

export type Config = {
  admin: AccountId32;
  baseInterestRate: bigint;
  optimalUtilization: bigint;
  slope1: bigint;
  slope2: bigint;
  boost: bigint;
  minStarsToVouch: number;
  cooldownPeriod: bigint;
  exposureCap: bigint;
  reserveFactor: number;
  maxRate: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type ConfigError = "NotAdmin";
